apiVersion: v2
name: opencode
description: opencode LanguageAgentRuntime for the Language Operator
type: application
version: 0.1.7
appVersion: "0.1.7"
keywords:
  - ai
  - llm
  - agents
  - opencode
home: https://github.com/language-operator/opencode-adapter
sources:
  - https://github.com/language-operator/opencode-adapter
maintainers:
  - name: James Ryan
    email: james@theryans.io
